"""empty message

Revision ID: 56c6d220b830
Revises: 
Create Date: 2018-11-03 11:33:57.439672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56c6d220b830'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Unicode(length=225), nullable=True),
    sa.Column('auther', sa.Unicode(length=225), nullable=True),
    sa.Column('publisher', sa.Unicode(length=225), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Unicode(length=225), nullable=True),
    sa.Column('book_title', sa.Unicode(length=225), nullable=True),
    sa.Column('implession', sa.UnicodeText(), nullable=True),
    sa.ForeignKeyConstraint(['book_title'], ['books.title'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('diary')
    op.drop_table('books')
    # ### end Alembic commands ###
